---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 12
    #  kafkaClusterRef:
    #    name: kafka
    #    namespace: confluent
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: mds-client
---
# rolebinding `testadmin-rb` allows `testadmin` to see kafkaCluster
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testadmin-test-topic-rb
  namespace: confluent
spec:
  principal:
    type: user
    name: testadmin
  role: ResourceOwner
  resourcePatterns:
    - name: test
      resourceType: Topic
      patternType: LITERAL

  ## if use other kafkaRestClass except for default, need to configure accordingly
  #kafkaRestClassRef:
  # name: default
